on:
  push:
    branches:
      - "main"

jobs:
  compile:
    name: Compile site assets
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/pgrange/cabal_test:main
          options: -v ${{ github.workspace }}:/src
          run: |
            cabal build all
